const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const ids=['f-price','f-cost','s-price','s-cost','payroll','rent','marketing','other-expense'];
const tbody=document.querySelector('#forecast-table tbody');
months.forEach((month,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<th scope="row">${month}</th><td><input type="number" min="0" step="1" data-key="fuel-${i}" aria-label="${month} fuel gallons" placeholder="0"></td><td><input type="number" min="0" step="1" data-key="store-${i}" aria-label="${month} store transactions" placeholder="0"></td>${Array(6).fill('<td>—</td>').join('')}`;tbody.append(tr)});
const fields=[...document.querySelectorAll('[data-note],[data-key],.assumptions input,[data-startup]')];
try{const saved=JSON.parse(localStorage.getItem('campuspitstop-worksheet')||'{}');fields.forEach(el=>{const key=el.dataset.note||el.dataset.key||el.dataset.startup||el.id;if(saved[key]!=null)el.value=saved[key]})}catch{}
const n=id=>Math.max(0,Number(document.getElementById(id).value)||0),m=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
function calculate(){const startup=[...document.querySelectorAll('[data-startup]')].reduce((sum,el)=>sum+Math.max(0,Number(el.value)||0),0);document.querySelector('#startup-total').textContent=m(startup);const totals=Array(6).fill(0);const fixed=n('payroll')+n('rent')+n('marketing')+n('other-expense');[...tbody.rows].forEach((row,i)=>{const gallons=Math.max(0,Number(row.querySelector('[data-key^=fuel]').value)||0),transactions=Math.max(0,Number(row.querySelector('[data-key^=store]').value)||0);const fuel=gallons*n('f-price'),store=transactions*n('s-price'),direct=gallons*n('f-cost')+transactions*n('s-cost'),gross=fuel+store-direct,profit=gross-fixed;[fuel,store,direct,gross,fixed,profit].forEach((v,j)=>{row.cells[j+3].textContent=m(v);totals[j]+=v})});document.querySelector('#forecast-table tfoot').innerHTML=`<tr><th scope="row">Annual total</th><td>—</td><td>—</td>${totals.map(v=>`<td>${m(v)}</td>`).join('')}</tr>`}
fields.forEach(el=>el.addEventListener('input',()=>{calculate();try{const values={};fields.forEach(f=>values[f.dataset.note||f.dataset.key||f.dataset.startup||f.id]=f.value);localStorage.setItem('campuspitstop-worksheet',JSON.stringify(values));document.querySelector('#save-status').textContent='Saved on this device.'}catch{document.querySelector('#save-status').textContent='This browser could not save your notes. Print or copy them before leaving.'}}));calculate();
const example={"f-price":3.59,"f-cost":3.23,"s-price":9,"s-cost":5.40,payroll:16000,rent:5000,marketing:800,"other-expense":2200};
const exampleFuel=[30000,32000,36000,39000,30000,20000,21000,39000,44000,43000,38000,24000];
const exampleStore=[1800,1900,2100,2300,1700,1100,1200,2300,2600,2500,2200,1400];
const exampleStartup={site:120000,equipment:650000,permits:50000,fitout:180000,inventory:45000,launch:10000};
function loadExample(){Object.entries(example).forEach(([id,value])=>document.getElementById(id).value=value);Object.entries(exampleStartup).forEach(([key,value])=>document.querySelector(`[data-startup="${key}"]`).value=value);months.forEach((_,i)=>{document.querySelector(`[data-key="fuel-${i}"]`).value=exampleFuel[i];document.querySelector(`[data-key="store-${i}"]`).value=exampleStore[i]});calculate();document.querySelector('#example-summary').textContent='UNT-area hypothetical Year 1: $1,629,540 sales; $225,720 gross profit; $62,280 operating loss. The separate illustrative startup total is $1,055,000; financing and taxes are excluded.';try{const values={};fields.forEach(f=>values[f.dataset.note||f.dataset.key||f.dataset.startup||f.id]=f.value);localStorage.setItem('campuspitstop-worksheet',JSON.stringify(values))}catch{}}
document.getElementById('load-example').addEventListener('click',loadExample);
const existingValues=fields.some(f=>f.value!=='');if(!existingValues)loadExample();
